FROM ucbd2k/grcalculator-docker:test_base_Rstudio

RUN R -e "remotes::install_github('uc-bd2k/GRmetrics', dependencies = F, ref = 'update')"
RUN R -e "remotes::install_github('uc-bd2k/shinyLi', dependencies = F)"

RUN git clone https://github.com/uc-bd2k/grcalculator.git
RUN git clone https://github.com/uc-bd2k/grbrowser.git
RUN git clone https://github.com/uc-bd2k/grtutorial.git

RUN cd grcalculator && git checkout update && cd ..
